version: '3'
networks:
  deqlms:
    driver: bridge
services:
  deqlms:
    image: "geoworks/deql-ms"
    container_name: deqlms
    restart: always
    labels:
      org.label-schema.group: "deql-ms"
    environment:
      db_options_host: postgis
    ports:
     - "3333:8888"
    networks:
      - deqlms
