version: '3'
networks:
  deqlms:
    driver: bridge
services:
################################
  ms-prisma:
    image: prismagraphql/prisma:1.8
    container_name: ms-prisma
    restart: always
    labels:
      org.label-schema.group: "ms-deps"
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ms-postgis
            port: 5432
            user: mspostgis
            password: mspostgis
            migrations: true
    networks:
      - deqlms
################################
  ms-postgis:
    image: "mdillon/postgis"
    container_name: ms-postgis
    restart: always
    environment:
      POSTGRES_USER: mspostgis
      POSTGRES_PASSWORD: mspostgis
      POSTGRES_DB: prisma
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "5445:5432"
    networks:
      - deqlms
################################
  ms-pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "6543:80"
    networks:
      - deqlms
################################
  ms-redis:
    image: "geoworks/redis"
    container_name: ms-redis
    restart: always
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "32768:6379"
    networks:
      - deqlms
################################
