version: '3.5'
networks:
  deql-ms:
    name: deql-ms
    driver: bridge
services:
################################
  deql-ms-postgis:
    image: "mdillon/postgis"
    container_name: deql-ms-postgis
    restart: always
    environment:
      POSTGRES_USER: mspostgis
      POSTGRES_PASSWORD: mspostgis
      POSTGRES_DB: mapcam
    volumes:
    - /opt/postgres:/var/lib/postgresql/data
    logging:
      options:
        max-size: 50m
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "5445:5432"
    networks:
      - deql-ms
################################
  deql-ms-pgadmin:
    image: "dpage/pgadmin4"
    container_name: deql-ms-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    logging:
      options:
        max-size: 50m
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "6543:80"
    networks:
      - deql-ms
################################
  deql-ms-redis:
    image: "geoworks/redis"
    container_name: deql-ms-redis
    restart: always
    logging:
      options:
        max-size: 50m
    labels:
      org.label-schema.group: "ms-deps"
    ports:
     - "32768:6379"
    networks:
      - deql-ms
################################
